### ISSUE TITLE
create new mongo collection (non-default)

### ISSUE THREAD

**Issue by prjemian** [prjemian/ipython-vm7#5]
Practice making a new mongodb collection, as if for multiple use of the server.

**Comment by prjemian** [comment]
revised `mongodb_config.yml` file:

```yaml
description: 'heavyweight shared database'
metadatastore:
    module: 'databroker.headersource.mongo'
    class: 'MDS'
    config:
        host: 'localhost'
        port: 27017
        # database: 'metadatastore-production-v1'
        database: 'bluesky-mintvm-headers'
        timezone: 'US/Central'
assets:
    module: 'databroker.assets.mongo'
    class: 'Registry'
    config:
        host: 'localhost'
        port: 27017
        # database: 'filestore-production-v1'
        database: 'bluesky-mintvm-assets'
```
